### ISSUE TITLE
Comparison with other libraries

### ISSUE THREAD

**Issue by dandv** [callmenick/five-star-rating#9]
How does this library compare to the [many other CSS rating libraries](https://github.com/dandv/comparisons/blob/master/star-rating-widgets.md)?

So far, I've noticed:

* no keyboard accessibility
* no half stars
* no support for tooltips/captions
* no animated selection feedback

**Comment by callmenick** [comment]
I'm not maintaining this at the moment. It was intended as an easy starter project for others to build off of. If I get back around to it, I'll address your pointers.
